M48
; DRILL file {KiCad 6.0.7-f9a2dced07~116~ubuntu22.04.1} date Fri 21 Oct 2022 11:38:13 BST
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-10-21T11:38:13+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,6.0.7-f9a2dced07~116~ubuntu22.04.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0866
%
G90
G05
T1
X5.8642Y-3.8976
T0
M30
