M48
; DRILL file {KiCad 7.0.7-7.0.7~ubuntu22.04.1} date Fri 08 Sep 2023 16:19:24 BST
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-09-08T16:19:24+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.7-7.0.7~ubuntu22.04.1
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1260
%
G90
G05
T1
X5.2165Y-3.1299
X8.1693Y-4.7047
T0
M30
